### ISSUE TITLE
MVC Architecture 

### ISSUE THREAD

**Issue by joelt11753** [joelt11753/RocketCard#14]
@cbeck

So, I am trying to keep it as simple and straightforward as possible.

Based on what we talked about Thursday, I am thinking that this is the structure to follow?

Models
* Users (with Devise)
* Company
* Timesheet

Controllers
* Admin namespace with multiple controllers to handle admin actions
* Employee namespace with multiple controllers to handle employee actions

With this approach, every time we introduce a new feature, we create a model that connects to an admin controller and an employee controller that deals with that data from the model.

**Comment by cbeck** [comment]
I think it's too simple. You are going to need more models. You will need something to track holidays / PTO for instance. There may be other things as well. It's nice to strive for simplicity in models, but I'd rather have a system with clearly defined objects that meet specific roles than try to shoehorn concepts into existing models for the sake of trying to keep things simple. In the end, you end up with a more complex system.

To me, a timesheet should just be that period's entries by a user. It may further be broken down into time entries, so a timesheet is really a collection of time entries. A time entry could have a day, start time and end time. A timesheet would have a period start and period end date. Then, you are introducing a system where an employee could have multiple time entries in a given day (say they don't get paid for lunch or had a doctor's appointment in the middle of the day and had to leave work for two hours). 

It SOUNDS more complex, but is actually easier in some regards. 

Ultimately, it's up to you. But remember, if you model it out in small pieces and use scaffolding to build CRUD for whatever your users see, then it doesn't matter how many objects you have.

**Comment by joelt11753** [comment]
@cbeck That sounds good. I like that approach.
