### ISSUE TITLE
#1 As a user I want to sign-up my company

### ISSUE THREAD

**Issue by joelt11753** [joelt11753/RocketCard#4]
After account creation user is redirected to company sign-up.

Requires Devise to sign-up a user.  Create a custom controller that inherits from Devise Registration.  This controller will handle adding the admin user and creating a company.  One form to ~~rule~~ handle them both, using this [http://theartandscienceofruby.com/2015/08/20/multiple-models-in-a-single-form/](http://theartandscienceofruby.com/2015/08/20/multiple-models-in-a-single-form/)

Controllers:
* Registration Controller
* Admin Namespace with default controller

Models:
* Company Model
* User Model (Devise)

User Steps:
1. User fills out form
2. Gets redirected to Admin dashboard
3. When admin users are logged in they go to admin dashboard

![home page](https://user-images.githubusercontent.com/13462105/32986920-604dfef2-cc91-11e7-940d-a4e142f23fdc.png)
![sign-up](https://image.ibb.co/gfoHSm/Sign_Up.png)
![dashboard](https://image.ibb.co/gLwhtR/Admin_Panel_First_Time_Login.png)

**Comment by joelt11753** [comment]
@cbeck 

Hey Chris how does this look?  They are not all done, but I am modeling them like this.

**Comment by cbeck** [comment]
These are looking good!
